### ISSUE TITLE
[Bug]: 进入下界传送门崩溃Game crashes when entering the nether portal

### ISSUE THREAD

**Issue by DC10-10** [Rad586/Forget-Me-Not#100]
### Descripiton 简述

进入下界传送门就会崩溃，新建存档测试仍然会崩溃

### Steps to reproduce. 复现问题的步骤

同上

### Screenshots 截图

[minecraft-exported-crash-info-2024-10-26T21-45-31.zip](https://github.com/user-attachments/files/17530813/minecraft-exported-crash-info-2024-10-26T21-45-31.zip)

### Logs 日志
https://gist.github.com/Rad586/5405cb6319b4ccdc6776c4024d652683

**Comment by Rad586** [comment]
试试升级到 2.10.0hf2，这个问题已经被修复过了。
Try updating the modpack to 2.10.0hf2, this crash has been already fixed iirc.
https://www.curseforge.com/minecraft/modpacks/forget-me-not/files/5799942
