### ISSUE TITLE
[Bug]:联机时使用带有非原版附魔的武器攻击房主时奔溃 Crash related to enchantments

### ISSUE THREAD

**Issue by ReKa-7** [Rad586/Forget-Me-Not#101]
### Descripiton 简述

联机时，只要使用带有非原版附魔的武器攻击房主就会奔溃

### Steps to reproduce. 复现问题的步骤

联机时使用带有非原版附魔的武器攻击房主

### Screenshots 截图

[错误报告-2024-10-26_21.20.21.zip](https://github.com/user-attachments/files/17532640/-2024-10-26_21.20.21.zip)

**Comment by Rad586** [comment]
Dulp of #97 
https://github.com/Rad586/Forget-Me-Not/issues/97#issuecomment-2395984897

**Comment by ReKa-7** [comment]
我就是最新版，但是还是奔溃
