### ISSUE TITLE
[Bug]:护甲附魔导致崩溃 Crash related to armor enchantment

### ISSUE THREAD

**Issue by sdahwdka** [Rad586/Forget-Me-Not#104]
### Descripiton 简述

前几天玩的时候还不存在这个问题，但是11月3号晚上玩的时候就出现了这个bug，进去打了一下我的朋友整个游戏就崩溃了，并且在mc百科里面使用了你说的方法并且按照要求去做了，但是还是存在这种问题，重启之类的方法我全部都试过，全部没用。

### Steps to reproduce. 复现问题的步骤

启动，进去游戏打一下联机的小伙伴就直接整个游戏闪退崩溃

**Comment by sdahwdka** [comment]
[Uploading minecraft-exported-crash-info-2024-11-04T00-41-49.zip…]()

**Comment by Rad586** [comment]
你没有成功上传文件，上传文件时等一会儿
You didn't uploaded the file successfully, wait for a while before it's done.

**Comment by sdahwdka** [comment]
[minecraft-exported-crash-info-2024-11-04T00-41-49.zip](https://github.com/user-attachments/files/17617657/minecraft-exported-crash-info-2024-11-04T00-41-49.zip)
这个可以了吗？

**Comment by sdahwdka** [comment]
麻烦你看一看了，谢谢，我试过和特殊附魔武器没关系，空手打也会这样

**Comment by Rad586** [comment]
感谢测试。
用这个文件替代 `enchantments.js` 即可（使用windows自带的文件名搜索功能，搜索文件名）。
Thanks for testing. Please try using this file to replace `enchantments.js`. You can use search function in windows to search the file name.
[enchantments.zip](https://github.com/user-attachments/files/17617977/enchantments.zip)

**Comment by Rad586** [comment]
![image](https://github.com/user-attachments/assets/6929f980-7a7e-484d-a59f-f3475a147855)

**Comment by sdahwdka** [comment]
好的，我试试

**Comment by sdahwdka** [comment]
[minecraft-exported-crash-info-2024-11-04T20-49-59.zip](https://github.com/user-attachments/files/17618294/minecraft-exported-crash-info-2024-11-04T20-49-59.zip) 
还是在崩溃，同样是空手去打

**Comment by sdahwdka** [comment]
已经成功解决了，谢谢作者大大，祝你天天开心！

**Comment by Rad586** [comment]
新版本（2.10.0+）将修复此问题
Will fix in new version(2.10.0+)
