### ISSUE TITLE
[Bug]: 求助！在liunx服务器上执行服务端LaunchServer.sh文件后报错。

### ISSUE THREAD

**Issue by gjbhmm** [Rad586/Forget-Me-Not#105]
### Descripiton 简述

使用./LaunchServer.sh执行LaunchServer.sh文件后触发以下报错

[root@lzsys seversForgetMeNot]# ./LaunchServer.sh

Printing Java version, if the Java version doesn't show below, your Java path is incorrect
java version "21.0.5" 2024-10-15 LTS
Java(TM) SE Runtime Environment (build 21.0.5+9-LTS-239)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.5+9-LTS-239, mixed mode, sharing)

Launching fabric-server-launch.jar with '8G' max memory, jvm args '-XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150' and arguments ''
Error: Unable to access jarfile fabric-server-launch.jar
Press any key to close...

### Steps to reproduce. 复现问题的步骤

1. 在curseforge上下载[ForgetMeNot 2.11.2 server.zip]上传到服务器解压
2. 使用./LaunchServer.sh 执行 LaunchServer.sh 文件后触发以下报错
3. 提示Error: Unable to access jarfile fabric-server-launch.jar

### Screenshots 截图

![1d97b1e5dafe319122e0af99ba763893](https://github.com/user-attachments/assets/636f8823-03e0-4b25-b12b-53a07b3c8650)
![QQ20241205-092111](https://github.com/user-attachments/assets/69fcba94-ed5a-457c-9e9a-8fd747ac73cc)
 
这里是文件夹与报错图

**Comment by Rad586** [comment]
这个服务端使用ATLauncher打包的，试试用它的linux版打开。
I used ATLauncher to create the serverpack, try running the serverpack with ATLauncher.
https://atlauncher.com/downloads

**Comment by gjbhmm** [comment]
十分感谢您的回复。

我安装您提供的连接在本地windows11系统上搜索Forget Me Not创建服务器

![QQ20241205-142605](https://github.com/user-attachments/assets/090cc6b7-bc5b-4773-9b0d-93a8f68f655d)


![569fa8861c555ab510b58c7f8e946ab6](https://github.com/user-attachments/assets/ffb47644-ad8e-43b6-994b-bc9a6e8cb631)

使用AT启动器在本地启动会出现报错

**Comment by Rad586** [comment]
应该是缺少必要文件。
新建一个1.19.2，fabric的服务端，打开它的文件夹，然后把服务端压缩包里的东西覆盖粘贴进去试试。
服务端的readme里有写。

Create a new instance of serverpack on 1.19.2 fabric, open its folder, copy the things in FMN serverpack, override the things in the folder, and it should work fine, as written in readme.
