### ISSUE TITLE
[Bug]: 钓鱼竿钓起来的鱼不会进入背包

### ISSUE THREAD

**Issue by kwoe2009** [Rad586/Forget-Me-Not#106]
### Descripiton 简述

钓鱼竿钓起来的鱼不会进入背包，而是在地上蹦跶，要杀死之后才能捡起来

### Steps to reproduce. 复现问题的步骤

1.准备一根钓鱼竿
2.钓上来一条鱼
3.发现鱼不会进入背包

### Screenshots 截图

![Uploading 2024-12-23_16.53.50.png…]()

**Comment by Rad586** [comment]
这是个整合包特性。
This is an intended feature.
