### ISSUE TITLE
穿过末地传送门时会判定死亡，重复穿过会扣除最大血量

### ISSUE THREAD

**Issue by EdmYouth** [Rad586/Forget-Me-Not#63]
### Descripiton 简述

新食物有限，而穿越末界门扣除最大血量则为无限制。能否取消（ForgetMeNot 2.3.0）（MC 1.19.2）（Fb 0.15.6）

### Steps to reproduce. 复现问题的步骤

新食物有限，而穿越末界门扣除最大血量则为无限制。能否取消（ForgetMeNot 2.3.0）（MC 1.19.2）（Fb 0.15.6）

**Comment by EdmYouth** [comment]
穿过末界门回主世界时背包多出一个追溯指针，次数过多依然会扣除最大生命值

**Comment by Rad586** [comment]
还没发布的2.4.0版本可能已经修复了这个问题。
我明天看下

**Comment by Rad586** [comment]
2.4.0已修复。
2.3.0的临时解决办法：搜索并删除`limited_lives.js`。

**Comment by Muxiaotong123** [comment]
穿过末地传送门时会清除玩家身上的所有效果，包括在末地使用药水后获得的效果（ForgetMeNot 2.5.0）（MC 1.19.2）（Fb 0.77.0）

**Comment by Rad586** [comment]
> 穿过末地传送门时会清除玩家身上的所有效果，包括在末地使用药水后获得的效果（ForgetMeNot 2.5.0）（MC 1.19.2）（Fb 0.77.0）

开了个新的。我测试一下。

**Comment by Rad586** [comment]
> > 穿过末地传送门时会清除玩家身上的所有效果，包括在末地使用药水后获得的效果（ForgetMeNot 2.5.0）（MC 1.19.2）（Fb 0.77.0）
> 
> 开了个新的（#68 ）。我测试一下。

已解决
