### ISSUE TITLE
生存模式出现永日，存档仍能正常运行 Daylight cycle stopped

### ISSUE THREAD

**Issue by EdmYouth** [Rad586/Forget-Me-Not#64]
（ForgetMeNot 2.3.0）（MC 1.19.2）（Fb 0.15.6）
生存模式中夜间右键床睡觉之后出现永日，太阳固定位置不会移动，无法昼夜交替，使用/time query day指令时无反馈，F3中“Local Difficulty:1.54 // 0.30(Day 0)”。存档仍可以正常运行
在此之前曾出现较久红色夜晚，天空正上方为较大红色正方形边框，对mod不太了解，不清楚是不是需要做什么任务或触发，遂使用指令/time set day 后恢复。不知是否有影响

**Comment by EdmYouth** [comment]
目前使用/time set day或ningh或noon时，时间依然无法流逝，太阳位置固定无法移动

**Comment by Rad586** [comment]
这个是100天的超级血月（月亮就是很大的红色方形）。直接用`/time set`指令会导致一些游戏规则没法恢复。
先执行`/time add 2497000`，然后再执行`/time set 0`就能恢复。

**Comment by EdmYouth** [comment]
> 这个是100天的超级血月（月亮就是很大的红色方形）。直接用指令会导致一些游戏规则没法恢复。 先执行，然后再执行就能恢复。`/time set``/time add 2497000``/time set 0`
> 
> 这是第100天的超级血月。使用会混淆脚本，导致一些异常。执行 ，然后修复此问题。`/time set``/time add 2497000``/time set 0`

此时需要依此输入这三条指令么？三条指令后是否回到超级血月？如何解除超级血月状态

**Comment by Rad586** [comment]
是，这是100天血月的设定，时间不够久或者没杀够怪，血月就不会落下。

**Comment by Rad586** [comment]
> > 这个是100天的超级血月（月亮就是很大的红色方形）。直接用指令会导致一些游戏规则没法恢复。 先执行，然后再执行就能恢复。`` /time set``/time add 2497000``/time set 0 ``
> > 这是第100天的超级血月。使用会混淆脚本，导致一些异常。执行 ，然后修复此问题。`` /time set``/time add 2497000``/time set 0 ``
> 
> 此时需要依此输入这三条指令么？三条指令后是否回到超级血月？如何解除超级血月状态

两条：
先：`/time add 2497000`
后：`/time set 0`

**Comment by Rad586** [comment]
笔记本电脑要没电了，如果还有后续问题我明天回答

**Comment by Rad586** [comment]
2.4.0已修复，超级血月期间执行时间相关命令将直接判定结束。
Fixed in 2.4.0, execute time related commands will directly finish the super blood moon.

**Comment by EdmYouth** [comment]
好的。非常感谢解答以及昨日夜间打扰。
另对两条指令仍有疑惑。顺序是否为：
1.先：/time set
2.后：/time add 2497000``/time set 0
但1的指令不是会被判定为非完整指令而提示错误么？

**Comment by Rad586** [comment]
先：/time add 2497000
后：/time set 0

**Comment by LinXin-L** [comment]
为啥我没见过，而且蓝月，金月，血月升起时，我的月亮都没变化，超级也是，而且血月升起反倒不刷怪了。我肯定玩过了100天，玩了一两月了

**Comment by Rad586** [comment]
> 为啥我没见过，而且蓝月，金月，血月升起时，我的月亮都没变化，超级也是，而且血月升起反倒不刷怪了。我肯定玩过了100天，玩了一两月了

因为脚本有改动，对于旧存档，如果已经过了100天，就不会再触发事件了
