### ISSUE TITLE
击杀末影龙过程中会出现末影龙悬停并静止，且音频出现卡频 

### ISSUE THREAD

**Issue by EdmYouth** [Rad586/Forget-Me-Not#65]
### Descripiton 简述

FNM2.3.0中两个存档末影龙战斗过程中，均疑似在末影龙进入二阶段期间出现悬停并停止一切行为，但近距离下玩家仍会受到攻击，玩家攻击也仍有效，且游戏音频出现卡频，但存档仍能继续运行，以及能够正常击杀。

### Steps to reproduce. 复现问题的步骤

如下图，此次重生末影龙后在即将击杀阶段悬停，并在模型双前肢中间出现特效闪烁

### Screenshots 截图

![微信截图_20240323225926](https://github.com/Rad586/Forget-Me-Not/assets/162459332/137d68c7-dd34-480d-a29a-fe2fe359ecae)

**Comment by Rad586** [comment]
那个是true ending数据包的效果，让你给它最后一击。
That's what true ending datapack does, hinting you to finish the ender dragon.
