### ISSUE TITLE
[Bug]: 连接服务器时显示连接已丢失并报错 Client crash related to cursery

### ISSUE THREAD

**Issue by GitHub-VAN** [Rad586/Forget-Me-Not#72]
### Descripiton 简述

如截图所示，登陆服务器时会出现此窗口并丢失连接。（我已经删除了music triggers、the impossible library这两个模组）

### Steps to reproduce. 复现问题的步骤

每次登录服务器都会出现此状况，重新安装了客户端仍无法解决此问题。

### Screenshots 截图

![image](https://github.com/Rad586/Forget-Me-Not/assets/147990382/4c76e5bd-9fc3-4699-b33b-bc2d808f1432)

### Logs 日志

https://gist.github.com/GitHub-VAN/0930e64f82c43c9daf5945724ad296fa

**Comment by Rad586** [comment]
应该是服务端与客户端版本不一致，也可能是我忘记两边都删除这个模组了。
两边都删除cursery模组就能解决。

**Comment by GitHub-VAN** [comment]
感谢回复，我试一下看看
________________________________
发件人: Rad ***@***.***>
发送时间: 2024年6月7日 14:42
收件人: Rad586/Forget-Me-Not ***@***.***>
抄送: GitHub-VAN ***@***.***>; Author ***@***.***>
主题: Re: [Rad586/Forget-Me-Not] [Bug]: 连接服务器时显示连接已丢失并报错 (Issue #72)


应该是服务端与客户端版本不一致，也可能是我忘记两边都删除这个模组了。
两边都删除cursery模组就能解决。

―

**Comment by GitHub-VAN** [comment]
![image](https://github.com/Rad586/Forget-Me-Not/assets/147990382/3bea2886-1a8c-4c7f-8d1f-2f109738b62d)
这次客户端在加载地形中会显示如上图
服务端删除了world文件后客户端再尝试登陆，会在加载地形时显示如下图
![image](https://github.com/Rad586/Forget-Me-Not/assets/147990382/02d83540-538d-4264-9d50-888628f9afcf)

**Comment by GitHub-VAN** [comment]
删除了stacker之后成功进入服务器，排查了好几天才发现，头大了...

**Comment by Rad586** [comment]
其实readme里写了
![image](https://github.com/Rad586/Forget-Me-Not/assets/99306685/69dd31ae-2f80-4f50-89d2-531fe9c50dcb)
