### ISSUE TITLE
[Bug]: 疑似未正确设置的主菜单界面 Gui of fancy meny not being hidden

### ISSUE THREAD

**Issue by Silvigarabis** [Rad586/Forget-Me-Not#77]
### Descripiton 简述

我刚刚尝试使用HMCL启动器下载了整合包的2.8.0版本并安装，在进入游戏后，发现多出来一个工具栏，简单研究后发现是FancyMenu用于辅助编辑的工具栏，这个工具栏似乎没有在整合包打包前关闭？

### Steps to reproduce. 复现问题的步骤

1. 使用HMCL启动器在整合包搜索页面，搜索“forget me not”，找到整合包，选择1.19.2的游戏版本，下载整合包2.8.0版本，安装
2. 启动刚刚下载的版本，等待游戏启动
3. 问题出现

### Screenshots 截图

![图片](https://github.com/user-attachments/assets/88e2108f-4d48-4b70-9b57-16bb3fd75741)
![图片](https://github.com/user-attachments/assets/a04338f0-1e06-48b2-8d58-a5657abbb6c9)
![IMG](https://github.com/user-attachments/assets/17b1b69d-3e8f-4f6b-9051-0b3339f1856d)

### Logs 日志

https://gist.github.com/Silvigarabis/78908e654783bc46dff7204fc543d82c

**Comment by Silvigarabis** [comment]
我刚刚下载了2.7.1版本的整合包进行测试，并没有这样的问题，这似乎是从2.8.0版本开始出现的

**Comment by Rad586** [comment]
> 我刚刚下载了2.7.1版本的整合包进行测试，并没有这样的问题，这似乎是从2.8.0版本开始出现的

忘记了，一会发个修复版

**Comment by Rad586** [comment]
Fixed in 2.8.0hf.
