### ISSUE TITLE
[Bug]: 使用建议的jvm参数启动游戏会崩溃

### ISSUE THREAD

**Issue by doubleyr** [Rad586/Forget-Me-Not#79]
### Descripiton 简述

因为在游戏中有时会出现突然掉帧的现象，所以尝试使用了作者提供的jvm参数，但每次都会在启动游戏的时候崩溃

### Steps to reproduce. 复现问题的步骤

打开hmcl启动器，选择该整合包，点击设置，编辑游戏特定设置，修改高级设置，，在java虚拟机参数一栏输入
-Xms6G -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:AllocatePrefetchStyle=1 -XX:ShenandoahGuaranteedGCInterval=1000000 -XX:+SegmentedCodeCache -XX:ReservedCodeCacheSize=188m -XX:NonProfiledCodeHeapSize=80m -XX:ProfiledCodeHeapSize=96m -XX:NonNMethodCodeHeapSize=12m -XX:MetaspaceSize=320m -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -XX:+UseNUMA -XX:+UseNewLongLShift -XX:+UseVectorCmov -XX:+UseFastStosb -XX:-DontCompileHugeMethods -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+UseLargePages -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority
，点击不添加默认的JVM参数，然后启动游戏，游戏意外退出

### Screenshots 截图

![QQ图片20240729124130](https://github.com/user-attachments/assets/01bb903a-6cf8-45bd-b294-9af7bb82a6ef)

### Logs 日志

https://gist.github.com/doubleyr/507caa39dcb2e202af1da100553867cb

**Comment by Silvigarabis** [comment]
也许作者还需要添加一个“推荐使用的Java”

**Comment by Rad586** [comment]
我的运行环境是 Zulu Java21。会在简介里加上的。
My environment is zulu java21. Will add a line about that in description.

https://www.azul.com/downloads/?version=java-21-lts&os=windows&architecture=x86-64-bit&package=jdk#zulu

**Comment by Rad586** [comment]
done
