### ISSUE TITLE
[Bug]: Some Bugs About Ore 一些关于矿石的错误

### ISSUE THREAD

**Issue by RouDen3** [Rad586/Forget-Me-Not#82]
### Descripiton 简述

如图，我在存档中发现了一些生成奇怪的矿物：
1. 如P1和P2，一些没有碰撞体积的矿物会随机生成在地表，这些矿物会有类似于沙子的性质（如P3）；
2. 如P4，我发现了一些生成在主世界的末影螨，它们会随机携带一个矿物，击杀它们会原地生成相应的矿物，可以被挖掘，掉落物也是真的。
原因未知。

### Steps to reproduce. 复现问题的步骤

1. 打开游戏。
2. 随机发现一些被错误生成的矿石。

### Screenshots 截图

P1 
![2024-08-06_14 47 15](https://github.com/user-attachments/assets/fd5ee0ec-1d2d-4fbc-b4ce-1861fcf00e83)
P2
![2024-08-06_14 52 31](https://github.com/user-attachments/assets/43d41e93-deb9-4b2d-98e9-d3caeaea5a8d)
P3
![2024-08-06_14 01 04](https://github.com/user-attachments/assets/99381e6d-712a-4b21-9a9c-42c5265410f2)
P4
![2024-08-06_14 07 35](https://github.com/user-attachments/assets/76d722d4-e5a7-41ba-820a-f020034ed916)

### Logs 日志

https://mclo.gs/dy85LEH

**Comment by Rad586** [comment]
我偷懒用了原版的实体，让矿石骑在上面，但似乎生成有些问题。
下个版本会换成正常的实体的。

I was lazy and used vanilla entity to carry these ores, they should spawn underground.
Will change to new entities in the next version.

**Comment by Rad586** [comment]
> 我偷懒用了原版的实体，让矿石骑在上面，但似乎生成有些问题。 下个版本会换成正常的实体的。
> 
> I was lazy and used vanilla entity to carry these ores, they should spawn underground. Will change to new entities in the next version.

我还不太会用 entityjs，考虑到我学习能力太差，下版本先移除，下下版本再加入新生物吧。
Well, I'm fresh to entityjs, and being a slow learner. Will remove the feature next version, and add new creatures in the coming version.

**Comment by Rad586** [comment]
Fixed in 2.10+.
