### ISSUE TITLE
[Bug]: 怎么关闭减少最高血量上限

### ISSUE THREAD

**Issue by ca7ttt** [Rad586/Forget-Me-Not#84]
### Descripiton 简述

怎么关闭死一次减少血量最高上限

### Steps to reproduce. 复现问题的步骤

已经要没有血了要玩不动了

**Comment by Rad586** [comment]
https://github.com/Rad586/Forget-Me-Not/discussions/76

**Comment by ca7ttt** [comment]
不好意思，我没找到，请你可以告诉我在哪里找吗？谢谢你

**Comment by ca7ttt** [comment]
不好意思，我没找到，请你可以告诉我在哪里找吗？谢谢你
