### ISSUE TITLE
[Bug]: A mod crashed on startup 启动游戏崩溃

### ISSUE THREAD

**Issue by 1433223tan** [Rad586/Forget-Me-Not#85]
### Descripiton 简述

我在正常游玩时,无意间触发了真实物理的ui乱飞的功能(这是我后面去查了我才知道的),我不知道怎么解决,ui按键乱飞导致我查看不了信息,于是我重启游戏客户端,再打开的时候发现打不开了,一直崩溃,说是mod unaverage_tweaks的崩溃

### Steps to reproduce. 复现问题的步骤

1.启用了Physics mod的ui物理功能.
2.重启了游戏
3.崩溃

### Screenshots 截图

![Snipaste_2024-08-19_23-54-57](https://github.com/user-attachments/assets/d997eb59-edda-451a-a187-26519b586b96)

### Logs 日志

[logs.zip](https://github.com/user-attachments/files/16666263/logs.zip)
我不知道发哪个我干脆把我logs压缩包发你了

**Comment by Rad586** [comment]
请发个日志文件

**Comment by Rad586** [comment]
另外，我记得把 physic 模组的那个彩蛋的按键改成了`scancode.999`，你的键盘上咋有这么个按键？？
Also, iirc, I changed the gui physic keybind to `scancode.999`, how the heck you trigger that??

**Comment by 1433223tan** [comment]
> 请发个日志文件。 日志文件位于游戏根目录的文件夹里。`logs`
> 
> 请发送游戏日志文件。游戏日志位于游戏根目录下的文件夹中。`logs`
> 
> ![图像](https://private-user-images.githubusercontent.com/99306685/359170398-d2d2403e-a819-4aa7-a13a-20a88613409a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDUzNzYsIm5iZiI6MTcyNDEwNTA3NiwicGF0aCI6Ii85OTMwNjY4NS8zNTkxNzAzOTgtZDJkMjQwM2UtYTgxOS00YWE3LWExM2EtMjBhODg2MTM0MDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIyMDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmE4OTIxOWZlYjljYzEyYTliNDE3ZDA2OTk4NjZmOTAxZTlkOWFmOTgyYzg1N2VlZDc4N2IxNWMzOWNmYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWPxAKCccO55V_Fir2_XSyjYBiGoIwLtyOoMh9WdOWY)

[logs.zip](https://github.com/user-attachments/files/16666295/logs.zip)

**Comment by 1433223tan** [comment]
我不知道发哪个我把我logs文件夹整个给你

**Comment by Rad586** [comment]
你可以搜索并发送`unaverage_tweaks.json`，发出来吗？它在`config`文件夹里。
Can you search and send `unaverage_tweaks.json`? It's in `config` folder.

**Comment by 1433223tan** [comment]
> 你可以搜索并发送`unaverage_tweaks.json`，发出来吗？它在`config`文件夹里。 Can you search and send `unaverage_tweaks.json`? It's in `config` folder.

[unaverage_tweaks.json](https://github.com/user-attachments/files/16679252/unaverage_tweaks.json)
你看看是不是这个

**Comment by Rad586** [comment]
不是。这个不是模组的配置文件，你发的是一个模组的代码。
如果这个就是在`.minecraft\config`下的文件，用这个替换它：
[unaverage_tweaks.json](https://github.com/user-attachments/files/16679531/unaverage_tweaks.json)

Definitely no. It's not a config file, it's the code of a mod.
If that's the thing under `.minecraft\config`, replace it with the file above.

**Comment by 1433223tan** [comment]
> 不是。这个不是模组的配置文件，你发的是一个模组的代码。 如果这个就是在`.minecraft\config`下的文件，用这个替换它： 谢谢作者大大,我已经解决这个问题了,游戏已经正常启动了,能告诉我这是什么原因导致的崩溃吗,我下次注意下不再次触发这个bug

**Comment by 1433223tan** [comment]
> 不是。这个不是模组的配置文件，你发的是一个模组的代码。 如果这个就是在`.minecraft\config`下的文件，用这个替换它： [unaverage_tweaks.json](https://github.com/user-attachments/files/16679531/unaverage_tweaks.json)
> 
> Definitely no. It's not a config file, it's the code of a mod. If that's the thing under `.minecraft\config`, replace it with the file above.

谢谢作者大大,我已经可以正常启动游戏了,请问这是什么原因导致出游戏崩溃,让我知道确保我下次不会再出这种问题
![Snipaste_2024-08-21_01-47-03](https://github.com/user-attachments/assets/eff62ea6-cf18-4aed-a31e-e28806599b2d)

**Comment by 1433223tan** [comment]
另外我使用的启动器是PCL2

**Comment by Rad586** [comment]
我也不知道是什么原因...搞不懂为什么模组的配置文件会被写入明文代码。
Idk why either...
