### ISSUE TITLE
[Bug]: 看到手持末影珍珠的僵尸之后游戏崩溃

### ISSUE THREAD

**Issue by charlote547** [Rad586/Forget-Me-Not#87]
### Descripiton 简述

本来在钓鱼，回头看到门外有一个手持末影珍珠的僵尸，我向他靠近随后游戏崩溃

### Steps to reproduce. 复现问题的步骤

反复进入游戏之后一直卡在看到面对僵尸的位置

**Comment by charlote547** [comment]
[错误报告-2024-8-24_11.20.38.zip](https://github.com/user-attachments/files/16735962/-2024-8-24_11.20.38.zip)

**Comment by Rad586** [comment]
1. 删除 Auditory 模组。
2. 不要使用服务端单人游戏，那样体验很不好。客户端的 2.9.0 版本还在审核。

1. Delete Auditory mod.
2. Don't use serverpack for singleplayer usage. 2.9.0 client is still being moderated by curseforge.

**Comment by Rad586** [comment]
Fixed in 2.9.0hf
