### ISSUE TITLE
[Bug]: 似乎是生成的僵尸导致游戏崩溃 Crash related to zombie ticking

### ISSUE THREAD

**Issue by charlote547** [Rad586/Forget-Me-Not#88]
### Descripiton 简述

我在矿洞中，游戏突然崩溃了

### Steps to reproduce. 复现问题的步骤

[错误报告-2024-9-15_21.02.13.zip](https://github.com/user-attachments/files/17005839/-2024-9-15_21.02.13.zip)

**Comment by Rad586** [comment]
僵尸不能添加用弓攻击的目标，我脚本写错了。
临时解决：搜索 `evolution.js`，并删除 `evoluted.goalSelector.addGoal(1, new RangedBowAttackGoal(evoluted, 1, 20, -1));` 这行。

Zombies cant have bow attack goals, I messed up with the script.
Temp solution: search `evolution.js`, and delete the line includes `evoluted.goalSelector.addGoal(1, new RangedBowAttackGoal(evoluted, 1, 20, -1));`.

**Comment by Rad586** [comment]
Fixed in 2.10+.
