### ISSUE TITLE
[Bug]: 睡觉时聊天栏输入框不清空 Chat can't be cleared when sleeping

### ISSUE THREAD

**Issue by Madin-David** [Rad586/Forget-Me-Not#89]
### Descripiton 简述

睡觉时聊天输入框应当在按下enter后清空并发送信息
但在按下enter后信息正常发出 聊天输入框并没有被清空

### Steps to reproduce. 复现问题的步骤

1.点击床入睡
2.在输入框随便输什么
3.按enter发送
即可观测到输入框不清空

**Comment by Rad586** [comment]
这个本来是“保留聊天框输入”的功能，应该是有bug，2.10+会禁用，作为修复。

It's caused by "chat persistent text" feature, but seems it bugged. Disabled in 2.10+ as a fix.
