### ISSUE TITLE
[Bug]: 在末地打龙，打一半退出之后在进入会崩溃 Crash related to enchantment

### ISSUE THREAD

**Issue by tws135320** [Rad586/Forget-Me-Not#90]
### Descripiton 简述

在末地打龙，打一半退出之后在进入会崩溃

### Steps to reproduce. 复现问题的步骤

1，进入末地打龙，打掉水晶，再退出去
2，在进入就会显示程序未响应或者直接保存退出
[minecraft-exported-logs-2024-09-17T13-06-08.log](https://github.com/user-attachments/files/17023160/minecraft-exported-logs-2024-09-17T13-06-08.log)

**Comment by Rad586** [comment]
请发送 `logs`，或 `crash-reports` 文件夹下的日志文件，你提供的日志文件没有任何堆栈跟踪信息。
Please send log file in `logs` or `crash-reports` folder, the file you upload doesn't contain any stacktrace info.

**Comment by tws135320** [comment]
[minecraft-exported-crash-info-2024-09-17T13-05-37.zip](https://github.com/user-attachments/files/17023275/minecraft-exported-crash-info-2024-09-17T13-05-37.zip)

**Comment by Rad586** [comment]
搜索 `globals_function.js` 并替换成这个压缩包里的文件：
Search and replace `globals_function.js` with the file within: 
[globals_function.zip](https://github.com/user-attachments/files/17023346/globals_function.zip)

**Comment by Rad586** [comment]
崩溃原因是：我没有给附魔的脚本加上客户端的检查。会在2.10+修复。
It crashes because I didnt add a check for client side in enchantment scripts. Will be fixed in 2.10+.

**Comment by Rad586** [comment]
Fixed in 2.10+.
