### ISSUE TITLE
[Bug]: 树叶颜色不一致 Inconsistency in leaves' color

### ISSUE THREAD

**Issue by kwoe8823** [Rad586/Forget-Me-Not#91]
### Descripiton 简述

我想使用更多颜色的树叶装修房子，但是无论它本来颜色是怎样的，带回家后都是绿色树叶

### Steps to reproduce. 复现问题的步骤

p1 用剪刀在樱花树上剪下叶子
p2 叶子掉在地上的样子
p3 离开樱花群系后把叶子摆在地上的样子

### Screenshots 截图

![mmexport1726792723905](https://github.com/user-attachments/assets/b55eb611-ca5b-4708-b95c-b49cda27f16c)
![mmexport1726792728516](https://github.com/user-attachments/assets/63956391-8124-4225-b7ce-d1bddad05661)
![mmexport1726792732025](https://github.com/user-attachments/assets/0ce8203c-7f0d-4dca-92e8-25efeaf47aa1)

**Comment by kwoe8823** [comment]
如果把剪下来的樱花树叶就地放置，它的颜色会是本来的粉色

**Comment by Rad586** [comment]
这个实际上是群系颜色下的原版树叶。我会考虑解决办法的（比如染料+树叶＝彩色树叶）。
These are actually vanilla leaves, but tinted by biome color. I'll try solving this(e.g. dye + leaves = dyed leaves).

**Comment by Rad586** [comment]
Done. Dyeable leaves, 2.10+
![image](https://github.com/user-attachments/assets/fad55ca5-71da-491a-938e-bf061ab6e407)
