### ISSUE TITLE
[Bug]: 附魔武器打灾厄村民时存档崩了，现在都进不去

### ISSUE THREAD

**Issue by Xiuliu9926** [Rad586/Forget-Me-Not#97]
### Descripiton 简述

打个怪直接怪物崩了

### Steps to reproduce. 复现问题的步骤

[错误报告-2024-10-6_9.23.29.zip](https://github.com/user-attachments/files/17271372/-2024-10-6_9.23.29.zip)

**Comment by Xiuliu9926** [comment]
打个怪直接给我崩了，存档进不去，进去直接崩溃

**Comment by Rad586** [comment]
模组实体的问题。
临时解决：把这个文件粘贴到 `config` 文件夹里，**替代**原文件：
This is a crash due to modded entity.
Temp fix: paste this file into `config` folder, **replacing** the original file:

[mobifier.json](https://github.com/user-attachments/files/17272835/mobifier.json)

**Comment by Rad586** [comment]
不要忘记升级到 2.10.0 版本，那个版本也修复了一些崩溃。
Dont forget to update to 2.10.0, it fixed several crashes beside this.

**Comment by Rad586** [comment]
Fixed in 2.10.0hf.
